package com.whu.dao;

import com.whu.entity.book.Appointment;
import com.whu.entity.book.AppointmentExample;
import com.whu.entity.book.AppointmentKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AppointmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    int countByExample(AppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    int deleteByExample(AppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    int deleteByPrimaryKey(AppointmentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    int insert(Appointment record);
    int insertAppointment(AppointmentKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    int insertSelective(Appointment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    List<Appointment> selectByExample(AppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    Appointment selectByPrimaryKey(AppointmentKey key);
    List<Appointment> selectAll();
    List<Appointment> selectByUserId(int userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    int updateByExampleSelective(@Param("record") Appointment record, @Param("example") AppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    int updateByExample(@Param("record") Appointment record, @Param("example") AppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    int updateByPrimaryKeySelective(Appointment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    int updateByPrimaryKey(Appointment record);
}