package com.whu.entity.book;

import java.io.Serializable;

public class AppointmentKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.bookId
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    private Long bookid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.userID
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table appointment
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.bookId
     *
     * @return the value of appointment.bookId
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    public Long getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.bookId
     *
     * @param bookid the value for appointment.bookId
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    public void setBookid(Long bookid) {
        this.bookid = bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.userID
     *
     * @return the value of appointment.userID
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.userID
     *
     * @param userid the value for appointment.userID
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bookid=").append(bookid);
        sb.append(", userid=").append(userid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}