package com.whu.entity.book;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class Appointment extends AppointmentKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.appointTime
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date appointtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table appointment
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.appointTime
     *
     * @return the value of appointment.appointTime
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    public Date getAppointtime() {
        return appointtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.appointTime
     *
     * @param appointtime the value for appointment.appointTime
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    public void setAppointtime(Date appointtime) {
        this.appointtime = appointtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", appointtime=").append(appointtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}