package com.whu.entity.book;

import java.io.Serializable;

public class Book implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookId
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    private Long bookid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookName
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    private String bookname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookNumber
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    private Integer booknumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookId
     *
     * @return the value of book.bookId
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    public Long getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookId
     *
     * @param bookid the value for book.bookId
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    public void setBookid(Long bookid) {
        this.bookid = bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookName
     *
     * @return the value of book.bookName
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    public String getBookname() {
        return bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookName
     *
     * @param bookname the value for book.bookName
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    public void setBookname(String bookname) {
        this.bookname = bookname == null ? null : bookname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookNumber
     *
     * @return the value of book.bookNumber
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    public Integer getBooknumber() {
        return booknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookNumber
     *
     * @param booknumber the value for book.bookNumber
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    public void setBooknumber(Integer booknumber) {
        this.booknumber = booknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Sat Jul 06 22:26:26 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bookid=").append(bookid);
        sb.append(", bookname=").append(bookname);
        sb.append(", booknumber=").append(booknumber);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}